spring:
  datasource:
    url: jdbc:mysql://192.168.132.129:3306/service_a?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root


